#!/bin/bash
# monitor-http-status daemon
# chkconfig: 345 20 80

# Edit this line to send to a comma delimited list of emails you choose and a list of website URLs
SCRIPT="/usr/local/bin/monitor-http-status -v -e=someone@example.com -u=https://example.com,https://subsite.example.com"

NAME=monitor-http-status
RUNAS=monitor-http-status
PIDFILE=/var/run/$NAME.pid
LOGFILE=/var/log/$NAME.log

start() {
  echo 'Starting service…' >&2

  if [ ! -f "$LOGFILE" ]; then
    echo "Creating Log File $LOGFILE" >&2
    touch $LOGFILE
    chown $RUNAS $LOGFILE
  fi

  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

status() {
  if [ -f $PIDFILE ] && kill -0 $(cat "$PIDFILE"); then
    echo 'Service running' >&2
    return 1
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart}"
esac